.TH "C:/Users/ENVY 15/source/repos/Generics Directory Reference" 3 "Sun Feb 19 2023" "Generics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/ENVY 15/source/repos/Generics Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBNumber\&.cs\fP"
.br
.ti -1c
.RI "file \fBProgram\&.cs\fP"
.br
.in -1c
