.TH "Generics.Program" 3 "Sun Feb 19 2023" "Generics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Generics.Program
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBProgram\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Generics from the source code\&.
