.TH "Generics" 3 "Sun Feb 19 2023" "Generics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Generics
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNumber\fP"
.br
.RI "A generic class that accepts only numeric types\&. "
.ti -1c
.RI "class \fBProgram\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Generics from the source code\&.
