.TH "Generics.Number< T >" 3 "Sun Feb 19 2023" "Generics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Generics.Number< T > \- A generic class that accepts only numeric types\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInsertionSort\fP (T[] array)"
.br
.RI "Sorts array in ascending order using Insertion Sort algorithm\&. "
.in -1c
.SH "Detailed Description"
.PP 
A generic class that accepts only numeric types\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP A numeric(integral, float, double) type
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIstruct\fP
.TP
\fIT\fP : \fIIComparable<T>\fP
.TP
\fIT\fP : \fIIEquatable<T>\fP
.TP
\fIT\fP : \fIIFormattable\fP
.TP
\fIT\fP : \fIIConvertible\fP
.PP
Definition at line \fB10\fP of file \fBNumber\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void \fBGenerics\&.Number\fP< T >\&.InsertionSort (T[] array)\fC [static]\fP"

.PP
Sorts array in ascending order using Insertion Sort algorithm\&. 
.PP
\fBParameters\fP
.RS 4
\fIarray\fP Array of numbers to be sorted
.RE
.PP

.PP
Definition at line \fB28\fP of file \fBNumber\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Generics from the source code\&.
