.TH "C:/Users/ENVY 15/source/repos/Generics/Number.cs" 3 "Sun Feb 19 2023" "Generics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/ENVY 15/source/repos/Generics/Number.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGenerics\&.Number< T >\fP"
.br
.RI "A generic class that accepts only numeric types\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBGenerics\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Generics from the source code\&.
