.TH "C:/Users/ENVY 15/source/repos/BankApplication/Application.cs" 3 "Mon Mar 27 2023" "Bank Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/ENVY 15/source/repos/BankApplication/Application.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBankApplication\&.Application\fP"
.br
.RI "Application functionalities, prompts and menus\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBankApplication\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "$ \fBn\fP [!]"
.br
.ti -1c
.RI "$ \fBnName\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$ n[!]"

.SS "$ nName"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bank Application from the source code\&.
