.TH "BankApplication.Account" 3 "Mon Mar 27 2023" "Bank Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BankApplication.Account \- Representation of customers account\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAccount\fP (string \fBaccountNumber\fP, \fBCustomer\fP \fBcustomer\fP, \fBAccountType\fP \fBtype\fP, string \fBtransactionPin\fP)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBaccountNumber\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBAccountType\fP \fBtype\fP\fC [get]\fP"
.br
.ti -1c
.RI "double \fBbalance\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBCustomer\fP \fBcustomer\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBtransactionPin\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Representation of customers account\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BankApplication\&.Account\&.Account (string accountNumber, \fBCustomer\fP customer, \fBAccountType\fP type, string transactionPin)"

.SH "Property Documentation"
.PP 
.SS "string BankApplication\&.Account\&.accountNumber\fC [get]\fP"

.SS "double BankApplication\&.Account\&.balance\fC [get]\fP, \fC [set]\fP"

.SS "\fBCustomer\fP BankApplication\&.Account\&.customer\fC [get]\fP"

.SS "string BankApplication\&.Account\&.transactionPin\fC [get]\fP, \fC [set]\fP"

.SS "\fBAccountType\fP BankApplication\&.Account\&.type\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Bank Application from the source code\&.
