.TH "BankApplication.Util" 3 "Mon Mar 27 2023" "Bank Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BankApplication.Util \- Utility functions required by the application\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBGenerateAccountNumber\fP ()"
.br
.RI "Generates a bank account for a new customer\&. "
.ti -1c
.RI "static string \fBHashString\fP (string text)"
.br
.RI "Generate a PBKDF2 hash\&. "
.ti -1c
.RI "static bool \fBVerifyHash\fP (string text, string hashedText)"
.br
.RI "Generates PBKDF2 hash of text and compares with hashedText to see if they match\&. "
.in -1c
.SH "Detailed Description"
.PP 
Utility functions required by the application\&. 
.SH "Member Function Documentation"
.PP 
.SS "static string BankApplication\&.Util\&.GenerateAccountNumber ()\fC [static]\fP"

.PP
Generates a bank account for a new customer\&. 
.PP
\fBReturns\fP
.RS 4
The generated account number
.RE
.PP

.SS "static string BankApplication\&.Util\&.HashString (string text)\fC [static]\fP"

.PP
Generate a PBKDF2 hash\&. 
.PP
\fBParameters\fP
.RS 4
\fItext\fP The string to convert into a PBKDF2 hash
.RE
.PP
\fBReturns\fP
.RS 4
The generated PBKDF2 hash
.RE
.PP

.SS "static bool BankApplication\&.Util\&.VerifyHash (string text, string hashedText)\fC [static]\fP"

.PP
Generates PBKDF2 hash of text and compares with hashedText to see if they match\&. 
.PP
\fBParameters\fP
.RS 4
\fItext\fP The string to convert into a PBKDF2 hash
.br
\fIhashedText\fP The hash to be compared with
.RE
.PP
\fBReturns\fP
.RS 4
\fCtrue\fP if hashes match, else \fCfalse\fP
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Bank Application from the source code\&.
