.TH "BankApplication.Transaction" 3 "Mon Mar 27 2023" "Bank Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BankApplication.Transaction \- All transactions that can be performed by bank application\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBDeposit\fP (\fBAccount\fP account, double amount)"
.br
.RI "Deposits money into the customers account\&. "
.ti -1c
.RI "static void \fBWithdraw\fP (\fBAccount\fP account, double amount)"
.br
.RI "Withdraws money from a customers account\&. "
.ti -1c
.RI "static void \fBTransfer\fP (\fBAccount\fP sender, string account, double amount)"
.br
.RI "Transfers money from one customer to another\&. "
.in -1c
.SH "Detailed Description"
.PP 
All transactions that can be performed by bank application\&. 
.SH "Member Function Documentation"
.PP 
.SS "static void BankApplication\&.Transaction\&.Deposit (\fBAccount\fP account, double amount)\fC [static]\fP"

.PP
Deposits money into the customers account\&. 
.PP
\fBParameters\fP
.RS 4
\fIaccount\fP The account to be credited
.br
\fIamount\fP A non-negative and non-zero number to be deposited
.RE
.PP

.SS "static void BankApplication\&.Transaction\&.Transfer (\fBAccount\fP sender, string account, double amount)\fC [static]\fP"

.PP
Transfers money from one customer to another\&. 
.PP
\fBParameters\fP
.RS 4
\fIsender\fP The account to be debited
.br
\fIaccount\fP The account to be credited
.br
\fIamount\fP A non-negative and non-zero number to be transfered
.RE
.PP

.SS "static void BankApplication\&.Transaction\&.Withdraw (\fBAccount\fP account, double amount)\fC [static]\fP"

.PP
Withdraws money from a customers account\&. 
.PP
\fBParameters\fP
.RS 4
\fIaccount\fP The account to be debited
.br
\fIamount\fP A non-negative and non-zero number to be withdrawn
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Bank Application from the source code\&.
