.TH "BankApplication.Customer" 3 "Mon Mar 27 2023" "Bank Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BankApplication.Customer \- Representation of a customer\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomer\fP (string \fBlastname\fP, string \fBfirstname\fP, string \fBpassword\fP)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBlastname\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBfirstname\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBpassword\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Representation of a customer\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BankApplication\&.Customer\&.Customer (string lastname, string firstname, string password)"

.SH "Property Documentation"
.PP 
.SS "string BankApplication\&.Customer\&.firstname\fC [get]\fP"

.SS "string BankApplication\&.Customer\&.lastname\fC [get]\fP"

.SS "string BankApplication\&.Customer\&.password\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Bank Application from the source code\&.
