.TH "BankApplication.AccountNotFoundException" 3 "Mon Mar 27 2023" "Bank Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BankApplication.AccountNotFoundException \- Exception thrown if an account cannot be found in the data store\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAccountNotFoundException\fP ()"
.br
.ti -1c
.RI "\fBAccountNotFoundException\fP (string accountNumber)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exception thrown if an account cannot be found in the data store\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BankApplication\&.AccountNotFoundException\&.AccountNotFoundException ()"

.SS "BankApplication\&.AccountNotFoundException\&.AccountNotFoundException (string accountNumber)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Bank Application from the source code\&.
