.TH "BankApplication.InvalidAmountException" 3 "Mon Mar 27 2023" "Bank Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BankApplication.InvalidAmountException \- Exception thrown if customer enters a non-positive amount\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInvalidAmountException\fP ()"
.br
.ti -1c
.RI "\fBInvalidAmountException\fP (double amount)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exception thrown if customer enters a non-positive amount\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BankApplication\&.InvalidAmountException\&.InvalidAmountException ()"

.SS "BankApplication\&.InvalidAmountException\&.InvalidAmountException (double amount)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Bank Application from the source code\&.
