.TH "BankApplication.Database" 3 "Mon Mar 27 2023" "Bank Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BankApplication.Database \- Simulation of a database system\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInitialize\fP ()"
.br
.RI "Loads account information from data store\&. "
.ti -1c
.RI "static void \fBInsert\fP (\fBAccount\fP account)"
.br
.RI "Adds a new account into the account list\&. "
.ti -1c
.RI "static void \fBUpdate\fP (\fBAccount\fP account)"
.br
.RI "Update data about an existing account\&. "
.ti -1c
.RI "static \fBAccount\fP \fBSearch\fP (string accountNumber)"
.br
.RI "Searches for an account in the data store\&. "
.ti -1c
.RI "static void \fBCommit\fP ()"
.br
.RI "Publish the account list to the data store\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static List< \fBAccount\fP > \fBaccounts\fP = new List<\fBAccount\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Simulation of a database system\&. 
.SH "Member Function Documentation"
.PP 
.SS "static void BankApplication\&.Database\&.Commit ()\fC [static]\fP"

.PP
Publish the account list to the data store\&. 
.SS "static void BankApplication\&.Database\&.Initialize ()\fC [static]\fP"

.PP
Loads account information from data store\&. 
.SS "static void BankApplication\&.Database\&.Insert (\fBAccount\fP account)\fC [static]\fP"

.PP
Adds a new account into the account list\&. 
.PP
\fBParameters\fP
.RS 4
\fIaccount\fP 
.RE
.PP

.SS "static \fBAccount\fP BankApplication\&.Database\&.Search (string accountNumber)\fC [static]\fP"

.PP
Searches for an account in the data store\&. 
.PP
\fBParameters\fP
.RS 4
\fIaccountNumber\fP Account to search for
.RE
.PP
\fBReturns\fP
.RS 4
If the account exists, it is returned; else \fCnull\fP
.RE
.PP

.SS "static void BankApplication\&.Database\&.Update (\fBAccount\fP account)\fC [static]\fP"

.PP
Update data about an existing account\&. 
.PP
\fBParameters\fP
.RS 4
\fIaccount\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "List<\fBAccount\fP> BankApplication\&.Database\&.accounts = new List<\fBAccount\fP>()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Bank Application from the source code\&.
