.TH "C:/Users/ENVY 15/source/repos/BankApplication/packages Directory Reference" 3 "Mon Mar 27 2023" "Bank Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/ENVY 15/source/repos/BankApplication/packages Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBSystem\&.Text\&.Json\&.7\&.0\&.2\fP"
.br
.in -1c
