.TH "C:/Users/ENVY 15/source/repos/BankApplication/obj/Debug Directory Reference" 3 "Mon Mar 27 2023" "Bank Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/ENVY 15/source/repos/BankApplication/obj/Debug Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.NETFramework,Version=v4\&.7\&.2\&.AssemblyAttributes\&.cs\fP"
.br
.in -1c
