.TH "C:/Users/ENVY 15/source/repos/BankApplication/Customer.cs" 3 "Mon Mar 27 2023" "Bank Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/ENVY 15/source/repos/BankApplication/Customer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBankApplication\&.Customer\fP"
.br
.RI "Representation of a customer\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBankApplication\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Bank Application from the source code\&.
