.TH "md__c___users__e_n_v_y_15_source_repos__bank_application_packages__system__text__json_7_0_2__r_e_a_d_m_e" 3 "Mon Mar 27 2023" "Bank Application" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c___users__e_n_v_y_15_source_repos__bank_application_packages__system__text__json_7_0_2__r_e_a_d_m_e \- About 
.PP
Provides high-performance and low-allocating types that serialize objects to JavaScript Object Notation (JSON) text and deserialize JSON text to objects, with UTF-8 support built-in\&. Also provides types to read and write JSON text encoded as UTF-8, and to create an in-memory document object model (DOM), that is read-only, for random access of the JSON elements within a structured view of the data\&.
.PP
The \fCSystem\&.Text\&.Json\fP library is built-in as part of the shared framework in \&.NET Runtime\&. The package can be installed when you need to use it in other target frameworks\&.
.PP
For more information, see the documentation:
.PP
.IP "\(bu" 2
\fCJSON serialization and deserialization in \&.NET\fP
.IP "\(bu" 2
\fCHow to serialize and deserialize JSON in \&.NET\fP
.IP "\(bu" 2
\fCSystem\&.Text\&.Json API reference\fP 
.PP

